# Generated by Django 5.2.6 on 2025-09-18 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.RemoveField(
            model_name='story',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='rating',
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='stories/media/'),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.story')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='stories.story')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
